learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

#TEMPLATE TAGGING GLOBAL NAME
app_name = 'basic_app'

urlpatterns = [
    url('relative/$',views.relative,name='relative'),
    url('other/$',views.other,name='other'),

]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from basic_app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/',include('basic_app.urls'))
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world','number':100}
    return render(request,'basic_app/index.html',context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container">
        <ul class="navbar-nav mr-auto">
          <li><a class="navbar-brand" href="{% url 'index' %}">
            <img src="https://media-exp1.licdn.com/dms/image/C5635AQEKdv6R1gsEXw/profile-framedphoto-shrink_100_100/0/1609740864013?e=1614272400&v=beta&t=minzFR7-yo0YWuDbNtN_QNNkt4zYe-ZTxiKWVjRBvTw" width="30" height="30" class="d-inline-block align-top" alt="">HYD</a></li>
          <li><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="nav-link" href="{% url 'basic_app:other'%}">Other</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">

      {% block body_block%}
      {% endblock %}


    </div>
  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% load %}
    {% block body_block %}
    <h1>HUO YINGDONG PROFILE</h1>
    <!-- <h2>This is index.html page showing!</h2> -->
    <h5>Content & Promotion Manager | iFree Group | 2019.6 to now | Guangzhou</h5>
    <h6>Promotion Planning</h6>
    <p>Plan promotion events for online travel booking, translate app UI in English, and other content. Manage to create up to 3 promotions monthly and monitor product lifecycle via data from GA and improve future promotion,</p>
    <h6>Content Management</h6>
    <p>  Follow up on the latest trends, do market research and analysis, and provide content planning. Collaborate and communicate efficiently with the product team, dev team, and design team. Responsible for EDM, Facebook, Instagram content. Keep up with 1 EDM and up to 4 posts weekly. Successfully increased followers by 450%,</p>
    <h6>Channel Promotion</h6>
    <p>Responsible for personalized planning. Provide content that fit each channel standard and user type. Make sure to follow up with planning and execution. Improve constantly channels through data analysis.</p>
    <h6>Customer Research</h6>
    <p>Improve customer experience using surveys, interviews, and other methods to gather user suggestions and need and follow up with implementation or change.</p>
    <h6>Site related to my working place and platform
    iFree Group site <a href="www.ifreegroup.com">www.ifreegroup.com</a> ebbly online booking site <a href="www.ebbly.com">www.ebbly.com</a></h6>
    {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>Nothing to see here yet...</h1>
      <img class="img-fluid" src="https://i.insider.com/5ec572ee4dca68618c6caec2?width=1100&format=jpeg&auto=webp" alt="Upcoming movies">
    {% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
    <a href="{% url 'basic_app:other' %}">THE OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">ADMIN</a>
    <a href="{% url 'index' %}">LINK TO INDEX</a>

  </body>
</html>